//! Generates the named character reference table from the unedited `entities.json` of the HTML Standard.
//!
//! Usage: `entities_gen <entities.json> <output.zig>`.
//! `zig build entities-generate` runs it and writes the output to `src/html/entities_table.zig`, which is committed.
//! The output is deterministic and already in `zig fmt` form: its entries are sorted by the UTF-16 code units of their names.
//! The program rejects any entry outside the shape that the tokenizer relies on:
//! a name of `&` followed by `[A-Za-z0-9]+;?`, one or two code points, and a `characters` string that encodes them.

const std = @import("std");
const Io = std.Io;
const Allocator = std.mem.Allocator;

const input_size_limit = 16 * 1024 * 1024;

const Item = struct {
    /// The name after `&`.
    name: []const u8,
    code_points: [2]u21,
    len: usize,

    /// Orders names by their UTF-16 code units. Every name is ASCII, so each byte is one code unit.
    fn lessThan(_: void, a: Item, b: Item) bool {
        const length = @min(a.name.len, b.name.len);
        for (a.name[0..length], b.name[0..length]) |x, y| {
            if (x != y) return @as(u16, x) < @as(u16, y);
        }
        return a.name.len < b.name.len;
    }
};

pub fn main(init: std.process.Init) !u8 {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 3) {
        std.debug.print("usage: entities_gen <entities.json> <output.zig>\n", .{});
        return 2;
    }
    const arena = init.arena.allocator();
    const bytes = try Io.Dir.cwd().readFileAlloc(init.io, args[1], arena, .limited(input_size_limit));
    const items = parse(arena, bytes) catch |err| {
        std.debug.print("entities_gen: {s}: {t}\n", .{ args[1], err });
        return 1;
    };
    std.mem.sort(Item, items, {}, Item.lessThan);
    for (items[1..], items[0 .. items.len - 1]) |item, previous| {
        if (!Item.lessThan({}, previous, item)) {
            std.debug.print("entities_gen: duplicate name {s}\n", .{item.name});
            return 1;
        }
    }

    const file = try Io.Dir.cwd().createFile(init.io, args[2], .{});
    defer file.close(init.io);
    var buffer: [64 * 1024]u8 = undefined;
    var file_writer = file.writer(init.io, &buffer);
    try write(&file_writer.interface, items);
    try file_writer.interface.flush();
    return 0;
}

fn parse(arena: Allocator, bytes: []const u8) ![]Item {
    const root = try std.json.parseFromSliceLeaky(std.json.Value, arena, bytes, .{ .duplicate_field_behavior = .@"error" });
    if (root != .object) return error.ExpectedObject;
    const items = try arena.alloc(Item, root.object.count());
    for (root.object.keys(), root.object.values(), items) |key, value, *item| {
        if (key.len < 2 or key[0] != '&') return error.InvalidName;
        const name = key[1..];
        const body = if (name[name.len - 1] == ';') name[0 .. name.len - 1] else name;
        if (body.len == 0) return error.InvalidName;
        for (body) |c| {
            if (!std.ascii.isAlphanumeric(c)) return error.InvalidName;
        }
        if (value != .object or value.object.count() != 2) return error.InvalidEntry;
        const code_points = value.object.get("codepoints") orelse return error.InvalidEntry;
        const characters = value.object.get("characters") orelse return error.InvalidEntry;
        if (code_points != .array or characters != .string) return error.InvalidEntry;
        const list = code_points.array.items;
        if (list.len < 1 or list.len > 2) return error.InvalidCodePoints;
        item.* = .{ .name = name, .code_points = .{ 0, 0 }, .len = list.len };
        var encoded: [8]u8 = undefined;
        var encoded_len: usize = 0;
        for (list, 0..) |entry, index| {
            if (entry != .integer or entry.integer < 0 or entry.integer > 0x10FFFF) return error.InvalidCodePoints;
            const code_point: u21 = @intCast(entry.integer);
            item.code_points[index] = code_point;
            encoded_len += std.unicode.utf8Encode(code_point, encoded[encoded_len..]) catch return error.InvalidCodePoints;
        }
        if (!std.mem.eql(u8, encoded[0..encoded_len], characters.string)) return error.CharactersDiffer;
    }
    return items;
}

fn write(writer: *Io.Writer, items: []const Item) Io.Writer.Error!void {
    var longest: usize = 0;
    for (items) |item| longest = @max(longest, item.name.len);
    try writer.writeAll(
        \\//! Generated by `src/html/entities_gen.zig` from `src/html/entities.json` through `zig build entities-generate`. Do not edit.
        \\
        \\pub const Entity = struct {
        \\    /// The name after `&`, which may end with `;`.
        \\    name: []const u8,
        \\    /// One or two code points.
        \\    code_points: []const u21,
        \\};
        \\
        \\
    );
    try writer.print("/// The length of the longest name in code units.\npub const max_name_len = {d};\n\n", .{longest});
    try writer.writeAll("/// Every named character reference, sorted by the UTF-16 code units of its name.\npub const entities = [_]Entity{\n");
    for (items) |item| {
        try writer.print("    .{{ .name = \"{s}\", .code_points = &.{{", .{item.name});
        if (item.len == 1) {
            try writer.print("0x{X}}} }},\n", .{item.code_points[0]});
        } else {
            try writer.print(" 0x{X}, 0x{X} }} }},\n", .{ item.code_points[0], item.code_points[1] });
        }
    }
    try writer.writeAll("};\n");
}
