/* Generated by tools/abi.mjs from api/fairpane.schema.json. Do not edit.
 * Run node tools/fairpane.mjs abi-generate after a schema change.
 * The size and every member offset that the schema implies for each structure, as C11 static assertions.
 * Include this file after fairpane.h in a C11 translation unit.
 */
#ifndef FAIRPANE_ABI_LAYOUT_H
#define FAIRPANE_ABI_LAYOUT_H

#include <stddef.h>
#include "fairpane.h"

_Static_assert(sizeof(void *) == 8 || sizeof(void *) == 4, "The schema implies layouts for 32-bit and 64-bit pointers only.");
_Static_assert(sizeof(size_t) == sizeof(void *), "The schema implies a range length as wide as a pointer.");

_Static_assert(sizeof(fp_capabilities) == 16, "fp_capabilities differs from the size that the schema implies.");
_Static_assert(offsetof(fp_capabilities, struct_size) == 0, "fp_capabilities.struct_size differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_capabilities, abi_revision) == 4, "fp_capabilities.abi_revision differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_capabilities, feature_bits) == 8, "fp_capabilities.feature_bits differs from the offset that the schema implies.");

_Static_assert(sizeof(fp_engine_options) == 16, "fp_engine_options differs from the size that the schema implies.");
_Static_assert(offsetof(fp_engine_options, struct_size) == 0, "fp_engine_options.struct_size differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_engine_options, max_outstanding_requests) == 4, "fp_engine_options.max_outstanding_requests differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_engine_options, max_response_body_bytes) == 8, "fp_engine_options.max_response_body_bytes differs from the offset that the schema implies.");

_Static_assert(sizeof(fp_document_info) == (sizeof(void *) == 8 ? 24 : 16), "fp_document_info differs from the size that the schema implies.");
_Static_assert(offsetof(fp_document_info, struct_size) == 0, "fp_document_info.struct_size differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_document_info, state) == 4, "fp_document_info.state differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_document_info, body) == 8, "fp_document_info.body differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_document_info, body_len) == (sizeof(void *) == 8 ? 16 : 12), "fp_document_info.body_len differs from the offset that the schema implies.");

_Static_assert(sizeof(fp_response) == (sizeof(void *) == 8 ? 32 : 24), "fp_response differs from the size that the schema implies.");
_Static_assert(offsetof(fp_response, struct_size) == 0, "fp_response.struct_size differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_response, version) == 4, "fp_response.version differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_response, request_id) == 8, "fp_response.request_id differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_response, body) == 16, "fp_response.body differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_response, body_len) == (sizeof(void *) == 8 ? 24 : 20), "fp_response.body_len differs from the offset that the schema implies.");

_Static_assert(sizeof(fp_step_outcome) == 32, "fp_step_outcome differs from the size that the schema implies.");
_Static_assert(offsetof(fp_step_outcome, struct_size) == 0, "fp_step_outcome.struct_size differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_step_outcome, work_remaining) == 4, "fp_step_outcome.work_remaining differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_step_outcome, applied) == 8, "fp_step_outcome.applied differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_step_outcome, events_ready) == 16, "fp_step_outcome.events_ready differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_step_outcome, next_deadline) == 24, "fp_step_outcome.next_deadline differs from the offset that the schema implies.");

_Static_assert(sizeof(fp_event) == (sizeof(void *) == 8 ? 56 : 48), "fp_event differs from the size that the schema implies.");
_Static_assert(offsetof(fp_event, struct_size) == 0, "fp_event.struct_size differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_event, kind) == 4, "fp_event.kind differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_event, document_id) == 8, "fp_event.document_id differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_event, request_id) == 16, "fp_event.request_id differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_event, request_kind) == 24, "fp_event.request_kind differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_event, request_version) == 28, "fp_event.request_version differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_event, document_state) == 32, "fp_event.document_state differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_event, reject_reason) == 36, "fp_event.reject_reason differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_event, url) == 40, "fp_event.url differs from the offset that the schema implies.");
_Static_assert(offsetof(fp_event, url_len) == (sizeof(void *) == 8 ? 48 : 44), "fp_event.url_len differs from the offset that the schema implies.");

#endif
