//! Unicode character properties from the Unicode 18.0.0 Character Database.
//! `tables.zig` is generated by `tools/ucd.mjs` from the files under `ucd/`, which keep their Unicode License v3 notice in `ucd/license.txt`.
//! Lookups allocate nothing. `reference_test.zig` is the independent reference path for every code point.

const std = @import("std");
const tables = @import("tables.zig");

pub const version = "18.0.0";

comptime {
    std.debug.assert(std.mem.eql(u8, version, tables.version));
}

/// `General_Category` (`gc`), limited to the 30 values that `DerivedGeneralCategory.txt` assigns. Tags are short aliases.
pub const GeneralCategory = tables.GeneralCategory;
/// `Script` (`sc`). Tags are short aliases in `PropertyValueAliases.txt` order.
pub const Script = tables.Script;
/// `Bidi_Class` (`bc`).
pub const BidiClass = tables.BidiClass;
/// `Joining_Type` (`jt`), from `DerivedJoiningType.txt`.
pub const JoiningType = tables.JoiningType;
/// `Indic_Syllabic_Category` (`InSC`).
pub const IndicSyllabicCategory = tables.IndicSyllabicCategory;
/// `Indic_Positional_Category` (`InPC`).
pub const IndicPositionalCategory = tables.IndicPositionalCategory;

pub const Properties = struct {
    gc: GeneralCategory,
    sc: Script,
    /// `Script_Extensions` in ascending `Script` order. A code point that `ScriptExtensions.txt` does not list has its `Script` value.
    scx: []const Script,
    bc: BidiClass,
    jt: JoiningType,
    insc: IndicSyllabicCategory,
    inpc: IndicPositionalCategory,
};

/// One single-element `Script_Extensions` set for each `Script` value.
const script_singletons = blk: {
    const scripts = std.meta.tags(Script);
    var sets: [scripts.len][1]Script = undefined;
    for (&sets, scripts) |*set, script| set.* = .{script};
    break :blk sets;
};

/// Returns the entry of the last range whose start is at most `code_point`. Every table starts at U+0000.
fn find(comptime R: type, ranges: []const R, code_point: u21) R {
    var low: usize = 0;
    var high: usize = ranges.len;
    while (high - low > 1) {
        const middle = low + (high - low) / 2;
        if (ranges[middle].start <= code_point) low = middle else high = middle;
    }
    return ranges[low];
}

/// Returns the seven properties of `code_point`, or `error.NotCodePoint` above U+10FFFF.
pub fn lookup(code_point: u21) error{NotCodePoint}!Properties {
    if (code_point > 0x10FFFF) return error.NotCodePoint;
    const sc = find(tables.Range(Script), &tables.script_ranges, code_point).value;
    const extension = find(tables.ScriptExtensionRange, &tables.script_extension_ranges, code_point).set;
    return .{
        .gc = find(tables.Range(GeneralCategory), &tables.general_category_ranges, code_point).value,
        .sc = sc,
        .scx = if (extension == tables.script_value) &script_singletons[@backingInt(sc)] else tables.script_extension_sets[extension],
        .bc = find(tables.Range(BidiClass), &tables.bidi_class_ranges, code_point).value,
        .jt = find(tables.Range(JoiningType), &tables.joining_type_ranges, code_point).value,
        .insc = find(tables.Range(IndicSyllabicCategory), &tables.indic_syllabic_category_ranges, code_point).value,
        .inpc = find(tables.Range(IndicPositionalCategory), &tables.indic_positional_category_ranges, code_point).value,
    };
}

comptime {
    for (.{
        tables.general_category_ranges,
        tables.script_ranges,
        tables.bidi_class_ranges,
        tables.joining_type_ranges,
        tables.indic_syllabic_category_ranges,
        tables.indic_positional_category_ranges,
        tables.script_extension_ranges,
    }) |ranges| std.debug.assert(ranges[0].start == 0);
}
