/* Generated by tools/abi.mjs from api/fairpane.schema.json. Do not edit.
 * Run node tools/fairpane.mjs abi-generate after a schema change.
 */
#ifndef FAIRPANE_H
#define FAIRPANE_H

#include <stddef.h>
#include <stdint.h>

#if defined(_WIN32) && defined(FAIRPANE_SHARED)
#  if defined(FAIRPANE_BUILD)
#    define FP_API __declspec(dllexport)
#  else
#    define FP_API __declspec(dllimport)
#  endif
#else
#  define FP_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Experimental ABI revision zero. No stability promise exists yet. See api/README.md for ownership rules and lifetimes. */
#define FP_ABI_REVISION UINT32_C(0)

/* A value that may be absent. Zero encodes absence, and the value itself is never zero. */
#define FP_OPTIONAL(type) type

/* Status codes. Every function except abi_revision returns one. */
/* The call succeeded. */
#define FP_STATUS_OK UINT32_C(0)
/* A null required pointer, a short structure or output size, or an unknown enumeration value. */
#define FP_STATUS_INVALID_ARGUMENT UINT32_C(1)
/* The identifier is not live in this engine. */
#define FP_STATUS_UNKNOWN_ID UINT32_C(2)
/* The request already has a queued answer. */
#define FP_STATUS_INVALID_STATE UINT32_C(3)
/* The response version differs from the request version. */
#define FP_STATUS_UNSUPPORTED_VERSION UINT32_C(4)
/* A request bound, a body bound, or an identifier space was exhausted. */
#define FP_STATUS_LIMIT_EXCEEDED UINT32_C(5)
/* An allocation failed. */
#define FP_STATUS_OUT_OF_MEMORY UINT32_C(6)
/* The caller is not the thread that created the engine. */
#define FP_STATUS_WRONG_THREAD UINT32_C(7)

/* Document states. */
/* No load has started. */
#define FP_DOCUMENT_EMPTY UINT32_C(1)
/* A request for the document's resource is outstanding. */
#define FP_DOCUMENT_LOADING UINT32_C(2)
/* A step applied a response, and the document holds its body. */
#define FP_DOCUMENT_LOADED UINT32_C(3)
/* A step applied a rejection or a host cancellation. */
#define FP_DOCUMENT_FAILED UINT32_C(4)

/* Host request kinds. */
/* A request for the bytes of a document's resource. */
#define FP_REQUEST_RESOURCE UINT32_C(1)

/* Rejection reasons. */
/* The host does not implement the request's version. */
#define FP_REJECT_UNSUPPORTED_VERSION UINT32_C(1)

/* Event kinds. */
/* No event was ready. */
#define FP_EVENT_NONE UINT32_C(0)
/* A load issued a request. */
#define FP_EVENT_REQUEST_ISSUED UINT32_C(1)
/* A request ended by cancellation. */
#define FP_EVENT_REQUEST_CANCELLED UINT32_C(2)
/* A document moved to a new state. */
#define FP_EVENT_DOCUMENT_STATE_CHANGED UINT32_C(3)

/* The only version of the resource request kind. */
#define FP_RESOURCE_REQUEST_VERSION UINT32_C(1)

/* The next deadline when no deadline exists. No timer exists yet, so every step reports it. */
#define FP_DEADLINE_NONE UINT64_C(0xFFFFFFFFFFFFFFFF)

/* An engine. It belongs to the thread that created it. */
typedef struct fp_engine fp_engine;

/* A document identifier. It is nonzero, unique within the process, and never reused. */
typedef uint64_t fp_document_id;

/* A request identifier. It is nonzero, unique within the process, and never reused. Document and request identifiers come from one sequence, so they never coincide. */
typedef uint64_t fp_request_id;

/* Output of query_capabilities. */
typedef struct fp_capabilities {
    uint32_t struct_size;
    uint32_t abi_revision;
    /* The implemented browser capabilities. The mask is zero in the bootstrap. */
    uint64_t feature_bits;
} fp_capabilities;

/* Input. struct_size must be at least the declared structure size. */
typedef struct fp_engine_options {
    uint32_t struct_size;
    /* The maximum number of requests that are outstanding at once. */
    uint32_t max_outstanding_requests;
    /* The maximum size of one response body in bytes. */
    uint64_t max_response_body_bytes;
} fp_engine_options;

/* Output of document_get. */
typedef struct fp_document_info {
    uint32_t struct_size;
    uint32_t state;
    /* The loaded body, or null when body_len is zero. The bytes stay readable until the document's next load or its destruction. */
    const uint8_t *body;
    size_t body_len;
} fp_document_info;

/* Input. struct_size must be at least the declared structure size. */
typedef struct fp_response {
    uint32_t struct_size;
    /* Must equal the request version. */
    uint32_t version;
    fp_request_id request_id;
    /* Borrowed for the call only. May be null when body_len is zero. */
    const uint8_t *body;
    size_t body_len;
} fp_response;

/* Output of engine_step. */
typedef struct fp_step_outcome {
    uint32_t struct_size;
    /* One when queued input remains, otherwise zero. */
    uint32_t work_remaining;
    /* The number of queued inputs that the step applied. */
    uint64_t applied;
    /* The number of events that are ready to drain. */
    uint64_t events_ready;
    /* Always the deadline_none constant. */
    uint64_t next_deadline;
} fp_step_outcome;

/* Output of engine_next_event. Fields that do not apply to the kind are zero or null. */
typedef struct fp_event {
    uint32_t struct_size;
    uint32_t kind;
    FP_OPTIONAL(fp_document_id) document_id;
    FP_OPTIONAL(fp_request_id) request_id;
    FP_OPTIONAL(uint32_t) request_kind;
    FP_OPTIONAL(uint32_t) request_version;
    /* The new state for a document_state_changed event. */
    FP_OPTIONAL(uint32_t) document_state;
    /* The rejection reason when an applied rejection failed the document. */
    FP_OPTIONAL(uint32_t) reject_reason;
    /* For a request_issued event, the request URL while the request is live, otherwise null. The bytes stay readable until the request ends. */
    const uint8_t *url;
    size_t url_len;
} fp_event;

/* Returns the ABI revision. */
FP_API uint32_t fp_abi_revision(void);

/* On success, this function initializes the declared capability structure. The feature mask is zero in the bootstrap. On an invalid size or a null output, no output bytes change. */
FP_API uint32_t fp_query_capabilities(fp_capabilities *out, size_t out_size);

/* Creates an engine on the calling thread and stores it in the output. */
FP_API uint32_t fp_engine_create(const fp_engine_options *options, fp_engine **out_engine);

/* Releases the engine and everything it owns, including outstanding requests, queued answers, undrained events, and every borrowed URL and body. */
FP_API uint32_t fp_engine_destroy(fp_engine *engine);

/* Creates an empty document and stores its identifier in the output. */
FP_API uint32_t fp_document_create(fp_engine *engine, fp_document_id *out_document);

/* Releases the document. An outstanding request is cancelled and announced, and its queued answer is discarded. */
FP_API uint32_t fp_document_destroy(fp_engine *engine, fp_document_id document);

/* Initializes the declared document information structure with the document state and body. */
FP_API uint32_t fp_document_get(fp_engine *engine, fp_document_id document, fp_document_info *out, size_t out_size);

/* Issues a version 1 resource request for a copy of url and stores its identifier in the output. The url buffer is borrowed for the call only and must not be null. A load while the document is loading cancels the earlier request. */
FP_API uint32_t fp_document_load(fp_engine *engine, fp_document_id document, const uint8_t *url, size_t url_len, fp_request_id *out_request);

/* Queues a response. The engine copies the body during the call. */
FP_API uint32_t fp_request_respond(fp_engine *engine, const fp_response *response);

/* Queues a rejection with a reject_reason value. */
FP_API uint32_t fp_request_reject(fp_engine *engine, fp_request_id request, uint32_t reason);

/* Queues the host's withdrawal of a request. */
FP_API uint32_t fp_request_cancel(fp_engine *engine, fp_request_id request);

/* Applies up to budget queued answers in arrival order. The budget is an engine scheduling boundary only. It creates no JavaScript task boundary. */
FP_API uint32_t fp_engine_step(fp_engine *engine, uint32_t budget, fp_step_outcome *out, size_t out_size);

/* Removes the oldest event and initializes the declared event structure with it. When no event is ready, the kind is none. */
FP_API uint32_t fp_engine_next_event(fp_engine *engine, fp_event *out, size_t out_size);

#ifdef __cplusplus
}
#endif
#endif
