#!/usr/bin/env node
/**
 * ABI schema, generator, and failure-scenario tests for FP-0021.
 * Run standalone with `node tools/abi.test.mjs`, or through `node tools/fairpane.mjs test`.
 * Cases 6, 7, and 8 also run in Zig and C through the `zig-test` and `c-abi` gates.
 * Their controller parts check that those sources cover the schema and every scenario.
 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import {
  AbiError, GENERATED_FILES, SCENARIOS_PATH, SCHEMA_PATH, generate, scenarioMarkers, structureLayout,
  validateScenarios, validateSchema, zigTypeName,
} from './abi.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const readText = relative => fs.readFileSync(path.join(root, relative), 'utf8');
const schema = () => JSON.parse(readText(SCHEMA_PATH));
const scenarios = () => JSON.parse(readText(SCENARIOS_PATH));
const named = (list, name) => list.find(item => item.name === name);
const u32 = { kind: 'integer', bits: 32, signed: false, range: [0, 4294967295] };
const temporary = [];

function temp() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fairpane-abi-'));
  temporary.push(dir); return dir;
}
function rejects(fn, pattern) {
  assert.throws(fn, e => {
    assert.ok(e instanceof AbiError, `Expected an AbiError, got ${e?.stack ?? e}`);
    assert.match(e.message, pattern);
    return true;
  });
}
/** Rebuild every object with its keys in reverse order. Arrays keep their order. */
function reverseKeys(value) {
  if (Array.isArray(value)) return value.map(reverseKeys);
  if (value === null || typeof value !== 'object') return value;
  return Object.fromEntries(Object.keys(value).reverse().map(key => [key, reverseKeys(value[key])]));
}
/** Copy the controller, the schema, the scenarios, and the generated files into a fresh directory. */
function controllerCopy() {
  const dir = temp();
  const files = [SCHEMA_PATH, SCENARIOS_PATH, ...GENERATED_FILES,
    ...fs.readdirSync(path.join(root, 'tools')).filter(name => name.endsWith('.mjs')).map(name => `tools/${name}`)];
  for (const file of files) {
    fs.mkdirSync(path.join(dir, path.dirname(file)), { recursive: true });
    fs.copyFileSync(path.join(root, file), path.join(dir, file));
  }
  return dir;
}
function abiCheckIn(dir) {
  return spawnSync(process.execPath, [path.join(dir, 'tools/fairpane.mjs'), 'abi-check'], { cwd: dir, encoding: 'utf8', windowsHide: true });
}
/** Map each field of a generated C structure to the type part of its declaration. */
function cFields(header, name) {
  const block = header.split(`typedef struct ${name} {\n`)[1]?.split(`\n} ${name};`)[0];
  assert.ok(block, `The header declares no structure ${name}.`);
  return new Map(block.split('\n').filter(line => !/^\s*(\/\*|\*)/.test(line)).map(line => {
    const m = /^ {4}(.+?) ?(\w+);$/.exec(line);
    assert.ok(m, `Unexpected structure line: ${line}`);
    return [m[2], m[1]];
  }));
}
/** Map each field of a generated Zig extern structure to its type. */
function zigFields(source, name) {
  const block = source.split(`pub const ${name} = extern struct {\n`)[1]?.split('\n};')[0];
  assert.ok(block, `The Zig file declares no structure ${name}.`);
  return new Map(block.split('\n').filter(line => !/^\s*\/\/\//.test(line)).map(line => {
    const m = /^ {4}(\w+): (.+),$/.exec(line);
    assert.ok(m, `Unexpected structure line: ${line}`);
    return [m[1], m[2]];
  }));
}

export const abiCases = [
  ['FP-0021 case 1: Generating from the committed schema reproduces the committed include/fairpane.h and src/abi_generated.zig byte for byte', () => {
    const generated = generate(schema());
    assert.deepEqual(Object.keys(generated), GENERATED_FILES);
    for (const file of GENERATED_FILES) {
      assert.ok(Buffer.from(generated[file], 'utf8').equals(fs.readFileSync(path.join(root, file))), `${file} differs from the generator output.`);
    }
    assert.match(generated['include/fairpane.h'], /^\/\* Generated by tools\/abi\.mjs from api\/fairpane\.schema\.json\. Do not edit\./);
    assert.match(generated['src/abi_generated.zig'], /^\/\/! Generated by tools\/abi\.mjs from api\/fairpane\.schema\.json\. Do not edit\./);
    assert.equal(fs.existsSync(path.join(root, 'api/bootstrap.json')), false);
  }],
  ['FP-0021 case 2: Changing one byte of either generated file makes abi-check exit with status 1 and name the file', () => {
    const dir = controllerCopy();
    const clean = abiCheckIn(dir);
    assert.equal(clean.status, 0, clean.stdout + clean.stderr);
    for (const file of GENERATED_FILES) {
      const target = path.join(dir, file), original = fs.readFileSync(target), changed = Buffer.from(original);
      let at = Math.floor(changed.length / 2);
      while (!/[a-z]/.test(String.fromCharCode(changed[at]))) at++;
      changed[at] ^= 0x20;
      fs.writeFileSync(target, changed);
      const stale = abiCheckIn(dir);
      assert.equal(stale.status, 1, stale.stdout + stale.stderr);
      assert.ok(stale.stdout.includes(file), `abi-check did not name ${file}: ${stale.stdout}`);
      for (const other of GENERATED_FILES.filter(name => name !== file)) assert.ok(!stale.stdout.includes(other), `abi-check named the unchanged ${other}.`);
      fs.writeFileSync(target, original);
    }
    assert.equal(abiCheckIn(dir).status, 0);
  }],
  ['FP-0021 case 3: Generation is deterministic across two runs and across schema key order', () => {
    const first = generate(schema()), second = generate(schema()), reversed = generate(reverseKeys(schema()));
    for (const file of GENERATED_FILES) {
      assert.equal(second[file], first[file]);
      assert.equal(reversed[file], first[file]);
    }
    assert.notDeepEqual(Object.keys(reverseKeys(schema())), Object.keys(schema()));
  }],
  ['FP-0021 case 4: The validator rejects an unknown kind, a pointer without ownership or lifetime, an inverted range, a duplicate name, and a structure without struct_size', () => {
    validateSchema(schema());
    const unknownKind = schema();
    named(named(unknownKind.functions, 'engine_step').parameters, 'budget').type = { kind: 'pointer' };
    rejects(() => validateSchema(unknownKind), /engine_step\.budget.*unknown kind "pointer"/);
    const noOwnership = schema();
    delete named(named(noOwnership.functions, 'document_load').parameters, 'url').ownership;
    rejects(() => validateSchema(noOwnership), /document_load\.url.*ownership/);
    const noLifetime = schema();
    delete named(named(noLifetime.structures, 'document_info').fields, 'body').lifetime;
    rejects(() => validateSchema(noLifetime), /document_info\.body.*lifetime/);
    const inverted = schema();
    named(named(inverted.functions, 'engine_step').parameters, 'budget').type.range = [10, 1];
    rejects(() => validateSchema(inverted), /engine_step\.budget.*inverted range/);
    const duplicate = schema();
    duplicate.structures.push(structuredClone(named(duplicate.structures, 'event')));
    rejects(() => validateSchema(duplicate), /duplicate name "event"/);
    const duplicateC = schema();
    duplicateC.constants.push({ ...structuredClone(duplicateC.constants[0]), name: 'status_ok' });
    rejects(() => validateSchema(duplicateC), /duplicate name "FP_STATUS_OK"/);
    const unsized = schema();
    named(unsized.structures, 'response').fields.shift();
    rejects(() => validateSchema(unsized), /response.*struct_size/);
  }],
  ['FP-0021 case 5: The schema distinguishes text, web_string, bytes, identifier, handle, ranged integer, and optional values, and the generator maps each one to distinct C and Zig declarations', () => {
    const fixture = schema();
    const pointer = { direction: 'out', nullability: 'nullable', ownership: 'owned_by_engine', lifetime: 'engine_destroy' };
    fixture.structures.push({ name: 'kind_fixture', description: 'A fixture with one value of each kind.', fields: [
      { name: 'struct_size', type: u32 },
      { name: 'count', type: { kind: 'integer', bits: 32, signed: true, range: [-5, 5] } },
      { name: 'document', type: { kind: 'identifier', family: 'document' } },
      { name: 'engine', type: { kind: 'handle', handle: 'engine' }, ...pointer },
      { name: 'payload', type: { kind: 'bytes' }, ...pointer },
      { name: 'label', type: { kind: 'text' }, ...pointer },
      { name: 'title', type: { kind: 'web_string' }, ...pointer },
      { name: 'request', type: { kind: 'optional', absent: 'zero', value: { kind: 'identifier', family: 'request' } } },
    ] });
    validateSchema(fixture);
    const generated = generate(fixture);
    const c = cFields(generated['include/fairpane.h'], 'fp_kind_fixture');
    const zig = zigFields(generated['src/abi_generated.zig'], 'KindFixture');
    const expected = {
      count: ['int32_t', 'i32'], document: ['fp_document_id', 'DocumentId'], engine: ['fp_engine *', '?*Engine'],
      payload: ['const uint8_t *', '?[*]const u8'], label: ['const char *', '?[*]const c_char'],
      title: ['const uint16_t *', '?[*]const u16'], request: ['FP_OPTIONAL(fp_request_id)', 'Optional(RequestId)'],
    };
    for (const [field, [cType, zigType]] of Object.entries(expected)) {
      assert.equal(c.get(field), cType, `C field ${field}`);
      assert.equal(zig.get(field), zigType, `Zig field ${field}`);
    }
    for (const field of ['payload', 'label', 'title']) {
      assert.equal(c.get(`${field}_len`), 'size_t');
      assert.equal(zig.get(`${field}_len`), 'usize');
    }
    assert.equal(new Set(Object.keys(expected).map(field => c.get(field))).size, 7);
    assert.equal(new Set(Object.keys(expected).map(field => zig.get(field))).size, 7);
    const optionalZero = structuredClone(fixture);
    named(optionalZero.structures, 'kind_fixture').fields.at(-1).type.value = { kind: 'integer', bits: 32, signed: false, range: [0, 7] };
    rejects(() => validateSchema(optionalZero), /kind_fixture\.request.*zero/);
  }],
  ['FP-0021 case 6: The generated Zig declarations assert the size and every field offset of every structure', () => {
    const s = schema(), source = generate(s)['src/abi_generated.zig'];
    const expression = (wide, narrow) => wide === narrow ? `${wide}` : `layout(${wide}, ${narrow})`;
    for (const structure of s.structures) {
      const wide = structureLayout(s, structure.name, 8), narrow = structureLayout(s, structure.name, 4);
      const zig = zigTypeName(structure.name);
      assert.ok(source.includes(`if (@sizeOf(${zig}) != ${expression(wide.size, narrow.size)}) @compileError(`), `${zig} size`);
      assert.equal(wide.offsets.length, narrow.offsets.length);
      for (const [i, { name, offset }] of wide.offsets.entries()) {
        assert.ok(source.includes(`if (@offsetOf(${zig}, "${name}") != ${expression(offset, narrow.offsets[i].offset)}) @compileError(`), `${zig}.${name} offset`);
      }
    }
    // The C smoke test asserts these layouts against the generated header with static assertions.
    const at = (name, field) => structureLayout(s, name, 8).offsets.find(o => o.name === field).offset;
    assert.deepEqual(['capabilities', 'engine_options', 'step_outcome'].map(name => structureLayout(s, name, 8).size), [16, 16, 32]);
    assert.deepEqual([at('response', 'body'), at('document_info', 'body'), at('event', 'reject_reason'), at('event', 'url')], [16, 8, 36, 40]);
  }],
  ['FP-0021 case 7: The C smoke test runs every C-expressible failure scenario and names each identifier it covers', () => {
    const source = readText('tests/c/abi_smoke.c');
    assert.match(source, /^#include "fairpane\.h"$/m);
    const expected = scenarios().scenarios.filter(item => item.expressible_in_c).map(item => item.id);
    assert.ok(expected.length > 0);
    assert.deepEqual([...scenarioMarkers(source)].sort(), [...expected].sort());
    const main = source.split('int main(void) {')[1];
    assert.ok(main, 'The C smoke test has no main function.');
    for (const id of expected) assert.ok(main.includes(`    scenario_${id.replaceAll('-', '_')}();\n`), `main does not run ${id}.`);
  }],
  ['FP-0021 case 8: The Zig scenario test runs every failure scenario through the generated declarations', () => {
    const source = readText('src/abi_scenarios.zig');
    assert.match(source, /@import\("abi_generated\.zig"\)/);
    const expected = scenarios().scenarios.map(item => item.id);
    assert.deepEqual([...scenarioMarkers(source)].sort(), [...expected].sort());
    for (const id of expected) assert.match(source, new RegExp(`^test "Scenario ${id}: `, 'm'));
    assert.match(readText('src/root.zig'), /_ = @import\("abi_scenarios\.zig"\);/);
  }],
  ['FP-0021 case 9: Every failure scenario has an identifier, calls, and expected outcomes, and the validator rejects one without them', () => {
    const s = schema(), committed = scenarios();
    validateScenarios(committed, s);
    for (const item of committed.scenarios) {
      assert.match(item.id, /^[a-z0-9]+(?:-[a-z0-9]+)*$/);
      assert.ok(item.calls.length > 0 && item.effects.length > 0, item.id);
      for (const call of item.calls) assert.ok(call.function && call.status, item.id);
    }
    const mutate = change => { const copy = structuredClone(committed); change(copy.scenarios[0], copy); return copy; };
    rejects(() => validateScenarios(mutate(item => { delete item.id; }), s), /identifier/);
    rejects(() => validateScenarios(mutate(item => { item.calls = []; }), s), /calls/);
    rejects(() => validateScenarios(mutate(item => { delete item.calls; }), s), /calls/);
    rejects(() => validateScenarios(mutate(item => { delete item.effects; }), s), /effects/);
    rejects(() => validateScenarios(mutate(item => { delete item.calls[0].status; }), s), /status/);
    rejects(() => validateScenarios(mutate(item => { item.calls[0].function = 'fp_unknown'; }), s), /unknown function "fp_unknown"/);
    rejects(() => validateScenarios(mutate(item => { item.calls.push({ function: 'fp_abi_revision', arguments: 'none', status: 'ok' }); }), s), /fp_abi_revision.*status "ok"/);
    rejects(() => validateScenarios(mutate((item, copy) => { copy.scenarios.push(structuredClone(item)); }), s), /duplicate scenario/);
    rejects(() => validateScenarios(mutate((_, copy) => { copy.scenarios = copy.scenarios.filter(item => item.situation !== 'foreign_unwind'); }), s), /foreign_unwind/);
  }],
].map(([name, fn]) => ({ name, fn }));

export function removeAbiFixtures() {
  const failures = [];
  for (const dir of temporary.splice(0).reverse()) {
    try { fs.rmSync(dir, { recursive: true, force: true }); } catch (e) { failures.push(`${dir}: ${e.message}`); }
  }
  return failures;
}

if (process.argv[1] && fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url))) {
  console.log('TAP version 13');
  let failures = 0;
  for (const [i, c] of abiCases.entries()) {
    try { await c.fn(); console.log(`ok ${i + 1} - ${c.name}`); }
    catch (e) { failures++; console.log(`not ok ${i + 1} - ${c.name}\n  ---\n  message: ${JSON.stringify(e.message)}\n  ...`); }
  }
  for (const problem of removeAbiFixtures()) { failures++; console.error(`Temporary fixture cleanup failed: ${problem}`); }
  console.log(`1..${abiCases.length}\n# tests ${abiCases.length}\n# pass ${abiCases.length - failures}\n# fail ${failures}`);
  process.exitCode = failures ? 1 : 0;
}
