//! Generated by tools/abi.mjs from api/fairpane.schema.json. Do not edit.
//! Run `node tools/fairpane.mjs abi-generate` after a schema change.
//! Experimental ABI revision zero. No stability promise exists yet. See api/README.md for ownership rules and lifetimes.

const std = @import("std");

pub const abi_revision: u32 = 0;

/// Status codes. Every function except abi_revision returns one.
pub const Status = enum(u32) {
    /// The call succeeded.
    ok = 0,
    /// A null required pointer, a short structure or output size, or an unknown enumeration value.
    invalid_argument = 1,
    /// The identifier is not live in this engine.
    unknown_id = 2,
    /// The request already has a queued answer.
    invalid_state = 3,
    /// The response version differs from the request version.
    unsupported_version = 4,
    /// A request bound, a body bound, or an identifier space was exhausted.
    limit_exceeded = 5,
    /// An allocation failed.
    out_of_memory = 6,
    /// The caller is not the thread that created the engine.
    wrong_thread = 7,
};

/// Document states.
pub const DocumentState = enum(u32) {
    /// No load has started.
    empty = 1,
    /// A request for the document's resource is outstanding.
    loading = 2,
    /// A step applied a response, and the document holds its body.
    loaded = 3,
    /// A step applied a rejection or a host cancellation.
    failed = 4,
};

/// Host request kinds.
pub const RequestKind = enum(u32) {
    /// A request for the bytes of a document's resource.
    resource = 1,
};

/// Rejection reasons.
pub const RejectReason = enum(u32) {
    /// The host does not implement the request's version.
    unsupported_version = 1,
};

/// Event kinds.
pub const EventKind = enum(u32) {
    /// No event was ready.
    none = 0,
    /// A load issued a request.
    request_issued = 1,
    /// A request ended by cancellation.
    request_cancelled = 2,
    /// A document moved to a new state.
    document_state_changed = 3,
};

/// The only version of the resource request kind.
pub const resource_request_version: u32 = 1;

/// The next deadline when no deadline exists. No timer exists yet, so every step reports it.
pub const deadline_none: u64 = 0xFFFFFFFFFFFFFFFF;

/// An engine. It belongs to the thread that created it.
pub const Engine = opaque {};

/// A document identifier. It is nonzero, unique within the process, and never reused.
pub const DocumentId = enum(u64) { _ };

/// A request identifier. It is nonzero, unique within the process, and never reused. Document and request identifiers come from one sequence, so they never coincide.
pub const RequestId = enum(u64) { _ };

/// A value that may be absent. Zero encodes absence, and the value itself is never zero.
pub fn Optional(comptime T: type) type {
    const Raw = switch (@typeInfo(T)) {
        .int => T,
        .@"enum" => |info| info.tag_type,
        else => @compileError("An optional value needs an integer, enumeration, or identifier type."),
    };
    return enum(Raw) {
        absent = 0,
        _,

        /// Wraps a present value, which is never zero.
        pub fn of(value: T) @This() {
            const raw: Raw = if (@typeInfo(T) == .int) value else @backingInt(value);
            std.debug.assert(raw != 0);
            return @fromBackingInt(raw);
        }

        /// Returns the value, or null when it is absent or outside its enumeration.
        pub fn get(optional: @This()) ?T {
            if (optional == .absent) return null;
            const raw = @backingInt(optional);
            return if (@typeInfo(T) == .int) raw else std.enums.fromInt(T, raw);
        }
    };
}

/// Output of query_capabilities.
pub const Capabilities = extern struct {
    struct_size: u32,
    abi_revision: u32,
    /// The implemented browser capabilities. The mask is zero in the bootstrap.
    feature_bits: u64,
};

/// Input. struct_size must be at least the declared structure size.
pub const EngineOptions = extern struct {
    struct_size: u32,
    /// The maximum number of requests that are outstanding at once.
    max_outstanding_requests: u32,
    /// The maximum size of one response body in bytes.
    max_response_body_bytes: u64,
};

/// Output of document_get.
pub const DocumentInfo = extern struct {
    struct_size: u32,
    state: u32,
    /// The loaded body, or null when body_len is zero. The bytes stay readable until the document's next load or its destruction.
    body: ?[*]const u8,
    body_len: usize,
};

/// Input. struct_size must be at least the declared structure size.
pub const Response = extern struct {
    struct_size: u32,
    /// Must equal the request version.
    version: u32,
    request_id: RequestId,
    /// Borrowed for the call only. May be null when body_len is zero.
    body: ?[*]const u8,
    body_len: usize,
};

/// Output of engine_step.
pub const StepOutcome = extern struct {
    struct_size: u32,
    /// One when queued input remains, otherwise zero.
    work_remaining: u32,
    /// The number of queued inputs that the step applied.
    applied: u64,
    /// The number of events that are ready to drain.
    events_ready: u64,
    /// Always the deadline_none constant.
    next_deadline: u64,
};

/// Output of engine_next_event. Fields that do not apply to the kind are zero or null.
pub const Event = extern struct {
    struct_size: u32,
    kind: u32,
    document_id: Optional(DocumentId),
    request_id: Optional(RequestId),
    request_kind: Optional(RequestKind),
    request_version: Optional(u32),
    /// The new state for a document_state_changed event.
    document_state: Optional(DocumentState),
    /// The rejection reason when an applied rejection failed the document.
    reject_reason: Optional(RejectReason),
    /// For a request_issued event, the request URL while the request is live, otherwise null. The bytes stay readable until the request ends.
    url: ?[*]const u8,
    url_len: usize,
};

/// The C function types, by symbol name.
pub const functions = struct {
    /// Returns the ABI revision.
    pub const fp_abi_revision = fn () callconv(.c) u32;
    /// On success, this function initializes the declared capability structure. The feature mask is zero in the bootstrap. On an invalid size or a null output, no output bytes change.
    pub const fp_query_capabilities = fn (out: ?*Capabilities, out_size: usize) callconv(.c) u32;
    /// Creates an engine on the calling thread and stores it in the output.
    pub const fp_engine_create = fn (options: ?*const EngineOptions, out_engine: ?*?*Engine) callconv(.c) u32;
    /// Releases the engine and everything it owns, including outstanding requests, queued answers, undrained events, and every borrowed URL and body.
    pub const fp_engine_destroy = fn (engine: ?*Engine) callconv(.c) u32;
    /// Creates an empty document and stores its identifier in the output.
    pub const fp_document_create = fn (engine: ?*Engine, out_document: ?*DocumentId) callconv(.c) u32;
    /// Releases the document. An outstanding request is cancelled and announced, and its queued answer is discarded.
    pub const fp_document_destroy = fn (engine: ?*Engine, document: DocumentId) callconv(.c) u32;
    /// Initializes the declared document information structure with the document state and body.
    pub const fp_document_get = fn (engine: ?*Engine, document: DocumentId, out: ?*DocumentInfo, out_size: usize) callconv(.c) u32;
    /// Issues a version 1 resource request for a copy of url and stores its identifier in the output. The url buffer is borrowed for the call only and must not be null. A load while the document is loading cancels the earlier request.
    pub const fp_document_load = fn (engine: ?*Engine, document: DocumentId, url: ?[*]const u8, url_len: usize, out_request: ?*RequestId) callconv(.c) u32;
    /// Queues a response. The engine copies the body during the call.
    pub const fp_request_respond = fn (engine: ?*Engine, response: ?*const Response) callconv(.c) u32;
    /// Queues a rejection with a reject_reason value.
    pub const fp_request_reject = fn (engine: ?*Engine, request: RequestId, reason: u32) callconv(.c) u32;
    /// Queues the host's withdrawal of a request.
    pub const fp_request_cancel = fn (engine: ?*Engine, request: RequestId) callconv(.c) u32;
    /// Applies up to budget queued answers in arrival order. The budget is an engine scheduling boundary only. It creates no JavaScript task boundary.
    pub const fp_engine_step = fn (engine: ?*Engine, budget: u32, out: ?*StepOutcome, out_size: usize) callconv(.c) u32;
    /// Removes the oldest event and initializes the declared event structure with it. When no event is ready, the kind is none.
    pub const fp_engine_next_event = fn (engine: ?*Engine, out: ?*Event, out_size: usize) callconv(.c) u32;
};

/// Selects the layout value that the schema implies for the target pointer width.
fn layout(comptime wide: comptime_int, comptime narrow: comptime_int) comptime_int {
    return if (@sizeOf(usize) == 8) wide else narrow;
}

// The size and every field offset that the schema implies for each structure.
comptime {
    if (@sizeOf(usize) != 8 and @sizeOf(usize) != 4) @compileError("The schema implies layouts for 32-bit and 64-bit pointers only.");
    if (@sizeOf(Capabilities) != 16) @compileError("Capabilities differs from the size that the schema implies.");
    if (@offsetOf(Capabilities, "struct_size") != 0) @compileError("Capabilities.struct_size differs from the offset that the schema implies.");
    if (@offsetOf(Capabilities, "abi_revision") != 4) @compileError("Capabilities.abi_revision differs from the offset that the schema implies.");
    if (@offsetOf(Capabilities, "feature_bits") != 8) @compileError("Capabilities.feature_bits differs from the offset that the schema implies.");
    if (@sizeOf(EngineOptions) != 16) @compileError("EngineOptions differs from the size that the schema implies.");
    if (@offsetOf(EngineOptions, "struct_size") != 0) @compileError("EngineOptions.struct_size differs from the offset that the schema implies.");
    if (@offsetOf(EngineOptions, "max_outstanding_requests") != 4) @compileError("EngineOptions.max_outstanding_requests differs from the offset that the schema implies.");
    if (@offsetOf(EngineOptions, "max_response_body_bytes") != 8) @compileError("EngineOptions.max_response_body_bytes differs from the offset that the schema implies.");
    if (@sizeOf(DocumentInfo) != layout(24, 16)) @compileError("DocumentInfo differs from the size that the schema implies.");
    if (@offsetOf(DocumentInfo, "struct_size") != 0) @compileError("DocumentInfo.struct_size differs from the offset that the schema implies.");
    if (@offsetOf(DocumentInfo, "state") != 4) @compileError("DocumentInfo.state differs from the offset that the schema implies.");
    if (@offsetOf(DocumentInfo, "body") != 8) @compileError("DocumentInfo.body differs from the offset that the schema implies.");
    if (@offsetOf(DocumentInfo, "body_len") != layout(16, 12)) @compileError("DocumentInfo.body_len differs from the offset that the schema implies.");
    if (@sizeOf(Response) != layout(32, 24)) @compileError("Response differs from the size that the schema implies.");
    if (@offsetOf(Response, "struct_size") != 0) @compileError("Response.struct_size differs from the offset that the schema implies.");
    if (@offsetOf(Response, "version") != 4) @compileError("Response.version differs from the offset that the schema implies.");
    if (@offsetOf(Response, "request_id") != 8) @compileError("Response.request_id differs from the offset that the schema implies.");
    if (@offsetOf(Response, "body") != 16) @compileError("Response.body differs from the offset that the schema implies.");
    if (@offsetOf(Response, "body_len") != layout(24, 20)) @compileError("Response.body_len differs from the offset that the schema implies.");
    if (@sizeOf(StepOutcome) != 32) @compileError("StepOutcome differs from the size that the schema implies.");
    if (@offsetOf(StepOutcome, "struct_size") != 0) @compileError("StepOutcome.struct_size differs from the offset that the schema implies.");
    if (@offsetOf(StepOutcome, "work_remaining") != 4) @compileError("StepOutcome.work_remaining differs from the offset that the schema implies.");
    if (@offsetOf(StepOutcome, "applied") != 8) @compileError("StepOutcome.applied differs from the offset that the schema implies.");
    if (@offsetOf(StepOutcome, "events_ready") != 16) @compileError("StepOutcome.events_ready differs from the offset that the schema implies.");
    if (@offsetOf(StepOutcome, "next_deadline") != 24) @compileError("StepOutcome.next_deadline differs from the offset that the schema implies.");
    if (@sizeOf(Event) != layout(56, 48)) @compileError("Event differs from the size that the schema implies.");
    if (@offsetOf(Event, "struct_size") != 0) @compileError("Event.struct_size differs from the offset that the schema implies.");
    if (@offsetOf(Event, "kind") != 4) @compileError("Event.kind differs from the offset that the schema implies.");
    if (@offsetOf(Event, "document_id") != 8) @compileError("Event.document_id differs from the offset that the schema implies.");
    if (@offsetOf(Event, "request_id") != 16) @compileError("Event.request_id differs from the offset that the schema implies.");
    if (@offsetOf(Event, "request_kind") != 24) @compileError("Event.request_kind differs from the offset that the schema implies.");
    if (@offsetOf(Event, "request_version") != 28) @compileError("Event.request_version differs from the offset that the schema implies.");
    if (@offsetOf(Event, "document_state") != 32) @compileError("Event.document_state differs from the offset that the schema implies.");
    if (@offsetOf(Event, "reject_reason") != 36) @compileError("Event.reject_reason differs from the offset that the schema implies.");
    if (@offsetOf(Event, "url") != 40) @compileError("Event.url differs from the offset that the schema implies.");
    if (@offsetOf(Event, "url_len") != layout(48, 44)) @compileError("Event.url_len differs from the offset that the schema implies.");
}
